// Generated by CoffeeScript 1.6.3
var Common, app, io, job, server, tweetReader;

Common = require('lib/common');

job = new Common.cronJob({
  cronTime: '*/5 * * * * *',
  onTick: function() {
    return Common.log.info("Tick");
  },
  onComplete: function() {
    return Common.log.info("Stop");
  },
  start: false
});

app = Common.express();

server = Common.http.createServer(app);

io = require('socket.io').listen(server, Common.config.get('socket.io'));

tweetReader = require('routes/socket');

app.set('views', __dirname + '/views');

app.set('view engine', 'jade');

app.use(Common.express.favicon());

app.use(Common.express.logger('dev'));

app.use(app.router);

app.use(Common.express["static"](Common.path.join(__dirname, 'public')));

if (app.get('env') === 'development') {
  app.use(Common.express.errorHandler);
}

app.get('/tweets/:hashtag', Common.tweet);

server.listen(Common.config.get('port'), function() {
  var port;
  port = Common.config.get('port');
  Common.log.info("Express server listening on port " + port);
});

/*
//@ sourceMappingURL=app.map
*/
