// Generated by CoffeeScript 1.6.3
var Tweet, User;

Tweet = require('models/tweet').Tweet;

User = require('models/user').User;

exports.tweets = function(req, res, next) {
  var hashtag;
  hashtag = req.params.hashtag;
  if (typeof hashtag === "undefined") {

  } else {
    return Tweet.find({
      hashtag: hashtag
    }).populate('user').exec(function(err, tweets) {
      tweets = tweets.map(function(tweet) {
        return {
          id: tweet.user.id,
          screen_name: tweet.user.screen_name,
          text: tweet.text,
          image: tweet.user.profile_image_url,
          followers: parseInt(tweet.user.followers_count),
          "static": true
        };
      });
      res.json({
        tweets: tweets
      });
    });
  }
};

/*
//@ sourceMappingURL=tweet.map
*/
