// Generated by CoffeeScript 1.6.3
var config, mongoose, mongooseOpts, mongooseUri;

mongoose = require('mongoose');

config = require('config');

mongooseUri = config.get('mongoose:uri');

mongooseOpts = config.get('mongoose:options');

mongoose.connect(mongooseUri, mongooseOpts);

module.exports = mongoose;

/*
//@ sourceMappingURL=mongoose.map
*/
