// Generated by CoffeeScript 1.6.3
var Rx;

Rx = require('rx');

Rx.Node.fromTwitterStream = function(stream) {
  return Rx.Observable.create(function(observer) {
    var dataHandler, endHandler, errorHandler;
    dataHandler = function(data) {
      observer.onNext(data);
    };
    errorHandler = function(err) {
      observer.onError(err);
    };
    endHandler = function() {
      observer.onCompleted();
    };
    stream.addListener('tweet', dataHandler);
    stream.addListener('error', errorHandler);
    stream.addListener('end', endHandler);
    return function() {
      stream.removeListener('tweet', dataHandler);
      stream.removeListener('error', errorHandler);
      stream.removeListener('end', endHandler);
    };
  }).publish().refCount();
};

module.exports = Rx;

/*
//@ sourceMappingURL=rx.twitter.stream.map
*/
