// Generated by CoffeeScript 1.6.3
var Schema, TweetSchema, mongoose;

mongoose = require('lib/mongoose');

Schema = mongoose.Schema;

TweetSchema = new Schema({
  id: {
    type: Number,
    unique: true,
    required: true
  },
  hashtag: {
    type: String
  },
  text: {
    type: String
  },
  source: {
    type: String
  },
  retweted: {
    type: Boolean
  },
  retweet_count: {
    type: Number
  },
  created_at: {
    type: Date,
    "default": Date.now
  },
  user: {
    type: Schema.Types.ObjectId,
    ref: 'User'
  }
});

exports.Tweet = mongoose.model('Tweet', TweetSchema);

/*
//@ sourceMappingURL=tweet.map
*/
