// Generated by CoffeeScript 1.6.3
var Schema, UserSchema, mongoose;

mongoose = require('lib/mongoose');

Schema = mongoose.Schema;

UserSchema = new Schema({
  id: {
    type: Number,
    unique: true,
    required: true
  },
  name: {
    type: String
  },
  screen_name: {
    type: String
  },
  profile_image_url: {
    type: String
  },
  followers_count: {
    type: Number
  },
  created_at: {
    type: Date,
    "default": Date.now
  }
});

exports.User = mongoose.model('User', UserSchema);

/*
//@ sourceMappingURL=user.map
*/
